name: Pull Request - Maven Test
on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - id: Checkout
      name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - id: Fetch_all_branches
      name: Fetch all branches
      run: git fetch --all

    - id: Setup_JDK_21
      name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - id: Cache_Maven_Packages
      name: Cache Maven Packages
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Create settings.xml
      run: |
        echo '<settings>' > settings.xml
        echo '  <pluginGroups>' >> settings.xml
        echo '    <pluginGroup>org.sonarsource.scanner.maven</pluginGroup>' >> settings.xml
        echo '  </pluginGroups>' >> settings.xml
        echo '</settings>' >> settings.xml
    - id: Maven_Test
      name: Maven Test
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn clean verify -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=ir-msob -Dsonar.projectKey=ir-msob_jima-core sonar:sonar -P test,report,coverage -s settings.xml 
    - id: SonarCloud_Scan
      name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2.3.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
