name: Pull Request - Maven Test
on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - id: Checkout
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: Fetch_all_branches
        name: Fetch all branches
        run: git fetch --all

      - id: Setup_JDK_21
        name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - id: Cache_Maven_Packages
        name: Cache Maven Packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - id: Maven_Test
        name: Maven Test
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:${{ env.SONAR_MAVEN_PLUGIN_VERSION }}:sonar \
          -Dsonar.host.url=${{ env.SONAR_HOST_URL }} \
          -Dsonar.java.binaries=${{ env.SONAR_JAVA_BINARIES }} \
          -Dsonar.java.libraries=${{ env.SONAR_JAVA_LIBRARIES }} \
          -Dsonar.organization=${{ env.SONAR_ORGANIZATION }} \
          -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }} \
          -Dsonar.coverage.jacoco.xmlReportPaths=${{ env.SONAR_COVERAGE_JACOCO_XML_REPORT_PATHS }} \
          -P test,report,coverage